### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by bcskillings** [raivo-otp/macos-receiver#1]
Is this ready for install? If so, how does one go about installing it?

**Comment by tijme** [comment]
Hi @bcskillings, unfortunately the MacOS receiver is not yet finished. Therefore, it cannot be used at the moment.

**Comment by tijme** [comment]
Raivo OTP can now be installed from the MacOS app store: https://apps.apple.com/us/app/raivo-otp/id1498497896
