### ISSUE TITLE
MacOS 10.15 Catalina Support

### ISSUE THREAD

**Issue by martintjj** [raivo-otp/macos-receiver#10]
Hi, I'm on MacOS 10.15 and AppStore says just 11.0 and above supported. readme.md says otherwise with Caralina support, I tried to build myself on Xcode changing the minimum version and no luck :( Is there a way to use it? My Macbook doesn't support 11.0.

Thanks

**Comment by tijme** [comment]
Hi @martintjj,

Unfortunately, the MacOS app is built with a lot of MacOS 11.x+ features. So unfortunately it is no longer feasible for me to make it compatible with MacOS 10.x. I've updated the readme accordingly.

Hope you understand 🙏
