### ISSUE TITLE
How to enable synchronization?

### ISSUE THREAD

**Issue by haltlos** [raivo-otp/macos-receiver#13]
Under Ravio OTP Settings, there is no option to enable settings. How to enable it?

How does the toggle button under iOS Settings > [person] > iCloud relate to the app? Why is the toggle button is on, when synchronization is disabled in the app?

**Comment by tijme** [comment]
Please see https://raivo-otp.com/faq/#how-do-i-configure-raivo-otp-for-macos-once-installed.

**Comment by haltlos** [comment]
I don’t realise the use case for a receiver yet. What does this do, that handoff does not already provide?

**Comment by tijme** [comment]
In contract to Handoff, the MacOS receiver works cross-iCloud account, without Bluetooth, and way is way faster.
