### ISSUE TITLE
New App Icon for macOS

### ISSUE THREAD

**Issue by sroepges** [raivo-otp/macos-receiver#17]
Hello,
I just recreated the app icon, like the iOS app icon.
I think it would look better in the Launchpad and will match with the other app icons.
If you want I can send you the psd file with all icon sizes. Let me know what you think.

<img src="https://user-images.githubusercontent.com/47949518/192647150-a4023f50-576d-4e94-91c6-88d3c7ada78f.png" alt="raivo-otp-app-icon" width="256px" />

**Comment by tijme** [comment]
Good catch, and interesting. I've never used launchpad before. I assume there can be two different icons for Raivo (1 for the launchpad and 1 for the menu bar).

Will update in the future.

**Comment by tijme** [comment]
Hey! I would like to implement the icon in the upcoming update. Could you share the PSD with me, that would be so lovely!

**Comment by tijme** [comment]
Will be released in version 1.0.5.
