### ISSUE TITLE
Hide "Raivo" Text in Menu Bar Icon

### ISSUE THREAD

**Issue by DrBrynzo** [raivo-otp/macos-receiver#18]
I just updated to Ventura today. After I rebooted I suddenly have the menu bar icon plus the text "Raivo" to the right of it. I saw an open issue about hiding the icon, but I would really like to just remove the "Raivo" text and leave the icon itself as it's using around 3x the space in the menu bar now.
![Screenshot 2022-10-30 at 9 31 32 PM](https://user-images.githubusercontent.com/37386883/198931500-cd154aba-684f-42c4-9f46-e36a805c66ae.png)

**Comment by tijme** [comment]
Good catch. Will update soon.

**Comment by tijme** [comment]
Fixed in ab3889e112b9a4ef3c01800ba933fa33ebb07e61, will update as version 1.0.5.
