### ISSUE TITLE
Error The QR-code does not appear to be from a MacOS Receiver.

### ISSUE THREAD

**Issue by JuanPerezPerez1** [raivo-otp/macos-receiver#2]
Hi
When I try to sync the app with mac i have this error in the ios app.

(Error The QR-code does not appear to be from a MacOS Receiver. )

thanks for making the app for mac

**Comment by tijme** [comment]
Are you scanning the QR-code via the Settings > Receivers screen in iOS? It should not be scanned the same way as you scan an OTP.

**Comment by JuanPerezPerez1** [comment]
Yes of course

**Comment by tijme** [comment]
Hmm that's weird. Would you be able to share the contents of the QR-code with me? You can blur or remove a part of the push token and encryption key. 

It helps me in debugging this issue.

**Comment by JuanPerezPerez1** [comment]
Uploading IMG_4696.MOV…

**Comment by JuanPerezPerez1** [comment]
https://user-images.githubusercontent.com/51170686/132096904-48c686e6-0f6c-4b7a-b774-03f01f29eda8.MOV

**Comment by tijme** [comment]
Sorry, I meant the actual contents of the QR code. If you scan it with a barcode scanner you will see the source of the QR code.

**Comment by JuanPerezPerez1** [comment]
![Captura de Pantalla 2021-09-04 a la(s) 10 59 35 a  m](https://user-images.githubusercontent.com/51170686/132099034-e7cf54f0-1238-451e-ad63-669f8b9592db.png)

**Comment by bcskillings** [comment]
I have the same issue![image](https://user-images.githubusercontent.com/31419498/132103907-469cf629-fda9-4f48-8378-408c0d26907e.jpeg)

**Comment by tijme** [comment]
Thanks to both of you for sharing. Would you be able to provide some environment details? The app versions, iOS/MacOS versions etc? I havent been able to replicate this issue yet.

**Comment by JuanPerezPerez1** [comment]
IOS 14.3 ,macOS Big Sur 11.5.2

**Comment by elliotsoomro** [comment]
I also have this issue. Using iOS 15.0 beta and macOS Big Sur 11.2.3

**Comment by tijme** [comment]
I've finally been able to replicate this issue. Thanks all for the bug report and provided information. 

Will be fixed in the next release!

**Comment by tijme** [comment]
If you update to 1.0.2 and scan again it should work. Could someone try?

**Comment by juancarrillofl** [comment]
Just updated both apps (iOS and MacOS) and it works! Thank you for your work :)

Tested on iOS 14.7.1 and MacOS 11.5.2.

**Comment by JuanPerezPerez1** [comment]
I have the same error with the last update.

**Comment by JuanPerezPerez1** [comment]
It work now!
