### ISSUE TITLE
Direct download link for macOS?

### ISSUE THREAD

**Issue by BingeCode** [raivo-otp/macos-receiver#23]
I would like to add the Raivo OTP application to the [homebrew](https://docs.brew.sh/Cask-Cookbook) ecosystem (as a small project of my own to get started with contributing to the Open Source community).

Could you provide me with a direct download link to the package/bundle? @tijme 

Thanks!

**Comment by bruteForceAttack** [comment]
I would appriciate that as well as the app store version is outdated.

**Comment by tijme** [comment]
Hello @BingeCode.

Unfortunately I don't provide builds like these at the moment. I havent found the right way to manage MacOS builds yet, apart from using the regular process via XCode and pushing it to TestFlight/AppStore directly.
