### ISSUE TITLE
Receive OTP codes independent from iOS clients

### ISSUE THREAD

**Issue by ShredderWalnut** [raivo-otp/macos-receiver#4]
Hello,

Coming from Authy, the single missing feature is the ability to receive OTP codes on the Mac independent from the iOS clients. Currently, it's inconvenient to have to pick up the phone instead of directly copying the code on the Mac, and even worse, if I happen to be unable to access the iOS clients, I would not be able to provide the code and log in.

Apologies if this is an unreasonable request, I read the GitHub repos and Reddit threads but didn't see this request come up.

**Comment by tijme** [comment]
Hi @ShredderWalnut,

Unfortunately this will not be implemented. The MacOS receiver was designed to only be able to receive tokens if you have access to a second-factor device (your iPhone). Having a password manager and a OTP manager with seeds on the same device would decrease the security level.

Hope you understand,
Tijme

**Comment by ShredderWalnut** [comment]
Hi @tijme, thank you for the explanation! I still have a question and hope you would kindly explain further.

Many password managers (Bitwarden, 1Password etc.) can sync across devices, which means the iPhone and iPad will have both the passwords and the OTP seeds on it. Why not provide the convenience of being able to store seeds and receive OTP on the Mac, since the security risk already exists on the iPhone and iPad anyway?

Thank you in advance for your patience and time.

**Comment by tijme** [comment]
Hi @ShredderWalnut,

IMO applications like 1Password do not adhere correctly to the MFA methodology, as if someone would compromise your account, they would have access to both your passwords and MFA seeds. That's why I don't want to implement a fully fledged app for MacOS. I want to keep passwords and MFA seeds on different locations, not in the same app/device.

**Comment by ShredderWalnut** [comment]
Hello @tijme, thanks for the reply!

Apologies if I did not make myself clear. I agree with your point and I also choose not to store seeds in my password manager. 

What I meant was that since the passwords (stored in passwords managers, e.g. 1Password) and the seeds (stored in Raivo) already is on the same iPhone, I don't think having the seeds on Raivo for Mac would undermine my security at all.

I understand if you stand by your decision. Thank you for your great work!

**Comment by ncodee** [comment]
Alright, It seems you’re decision is settled about this idea. 

However, I wanted to ask why the MacOS Receiver application is required for copying  codes between devices? Other apps such as 2fas are able to utilise the inbuilt os feature which syncs the clipboard between devices.

**Comment by ShredderWalnut** [comment]
Hi @ncodee,

From my personal experience, the Raivo receiver app is not *required* in order to paste 2FA codes on the Mac. 

I uninstalled the receiver app briefly after testing it and have had no problem copying codes from i(Pad)OS and pasting to macOS.

You might need to ensure the iCloud clipboard syncing feature is enabled somewhere, but the receiver app provides no additional value once you get that feature working.
