### ISSUE TITLE
Support for lower versions of MacOS

### ISSUE THREAD

**Issue by joadswelt** [raivo-otp/macos-receiver#5]
According to [this site,](https://gs.statcounter.com/macos-version-market-share/desktop/worldwide) many users of MacOS are still on versions lower than Big Sur, and many of us cannot update on our older computers. It would be fantastic if this app supported lower versions!

**Comment by tijme** [comment]
Hi @joadswelt,

I was not aware of these macOS usage details. Unfortunately, the MacOS app is built with a lot of MacOS 11.x+ features. So unfortunately it is no longer feasible for me to make it compatible with MacOS 10.x.
