### ISSUE TITLE
raivo otp 1.0.3 (12) won't launch on macOS Big Sur 11.6

### ISSUE THREAD

**Issue by fazzer4x** [raivo-otp/macos-receiver#6]
running on an MacAir M1. I can't launch Raivo after installing via App Store. 

iOS is working fine.

**Comment by fazzer4x** [comment]
User error: I didn't notice the app sitting in the menu bar.

**Comment by fazzer4x** [comment]
that would be great. Even if it's a brief popup, that would be great.

**Comment by aeroperf** [comment]
1. Thanks for posting this question and the solution
2. I too did not get it at first, did not notice it's in the menu bar -- UX improvement opportunity indeed!
